FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm ci --only=production

# Copy source code
COPY . .

ENV PORT=8080

# Expose port
EXPOSE 8080

# Start the application
CMD ["npm", "k8s-webhook"]

