### Scrap webhook

POST http://localhost:6429/scrap-webhook
content-type: application/json

{
    "message": "Hello, world!"
}


### Scrap webhook - prod

POST https://influencer-tracking-backend-240655696079.asia-south1.run.app/scrap-webhook
content-type: application/json

{
    "message": "Hello, world from cloud run!"
}